### ISSUE TITLE
Save info for observations and actions from user input

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#1664]
**This is part of the Policy Server** - #1665  This issue covers adding these to the DB (@brunovianarezende) and creating the forms (@fionnachan ). Please use a feature flag to enable/disable the UI parts.

### Context:

To run the policy as a REST endpoint, we need to generate some yaml files internally to make the endpoints friendlier to use. To fill out the yaml files need to gather certain information from the user or detect it automatically from the simulation model. 

These will be collected in the webapp UI in a similar way we ask users to provide names for reward variables.

### Action Names -  Example output.yml
```yml
0: move up
1: move right
2: move down
3: move left
```

This is a user-provided 'string' text label for each of the possible action outputs. (# possible actions)
This is used to provide a human-readable name for the output of the policy.

**For each possible action, the user provides**
**1. string text description of the action**

---
### Example schema.yaml

```yaml
Observation:
  type: "object"
  required:
    - mouse_row
    - mouse_col
  properties:
    mouse_row:
      type: "number"
      format: "float"
      example: 1
      minimum: 0
      maximum: 5
      description: "Vertical mouse position ('row') between 0 and 5"
    mouse_col:
      type: "number"
      format: "float"
      example: 2
      minimum: 0
      maximum: 5
      description: "Horizontal mouse position ('col') between 0 and 5"
```

**For each observation (number of observation), the user will provide:**
1. **a variable name. string These will be used in the JSON as the input to the REST endpoint.** 
1. **Short, human-readable description of the variable**
1.  **data type. enum?** 
1. **example value for the observation**
1. **min**
1. **max**

---

### Other notes
- These are set per model revision. 

  **Open question** - What do we do when a user uploads a new model revision? Can we detect or assume anything will be the same so we can pre-populate the info from a previous revision? Not that I can think of.

- What types of data types do we support? @pathmaykr
