### ISSUE TITLE
Overview of Policy Serving UI

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#1689]
This is part of the Policy Server

We need to gather certain information from the user or detect it automatically from the simulation model. These will be used to generate yml files that are required inputs to running the trained policy as a rest endpoint.

These will be collected in the webapp UI in a similar way we ask users to provide names for reward variables.

### Action Names -  output.yml
```yml
0: move up
1: move right
2: move down
3: move left
```

This is a user-provided 'string' text label for each of the possible action outputs. (# possible actions)
This is used to provide a human-readable name for the output of the policy.

---
### Observations - Schema.yml - 
---
### schema.yaml

```yaml
Observation:
  type: "object"
  required:
    - mouse_row
    - mouse_col
  properties:
    mouse_row:
      type: "number"
      format: "float"
      example: 1
      minimum: 0
      maximum: 5
      description: "Vertical mouse position ('row') between 0 and 5"
    mouse_col:
      type: "number"
      format: "float"
      example: 2
      minimum: 0
      maximum: 5
      description: "Horizontal mouse position ('col') between 0 and 5"
```

For each observable (number of observables), the user will provide:
1. a variable name. string These will be used in the JSON as the input to the REST endpoint. 
1. Short, human-readable description of the variable
1.  data type. enum? 
1. example value for the observation
1. min
1. max

**Preprocessor.py**
```py
def preprocess(obs):
    return [
        obs.get("id"),
        obs.get("coordinates")[0],
        obs.get("coordinates")[1],
        obs.get("has_up_neighbour"),
        obs.get("is_up_free"),
        obs.get("has_right_neighbour"),
        obs.get("is_right_free"),
    ]
```
The preprocessor takes those and puts them in the right order to be used internally.

In the most basic version, `preprocessor.py` is almost the same as the `getObservation()` function in the simulation. It takes different doubles and puts them in a fixed order.

Sometimes some processing needs to be done.
