### ISSUE TITLE
Create yml files for policy server

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#1690]
Part of policy server #1665 

To start the endpoint, we need two yaml files.

This task is to generate the two files from the inputs gathered and saved in #1664 . These files will be used as inputs for spinning up a rest endpoint. #1669 

The files are :
1. schema.yaml
1. output.yaml

### schema.yaml

```yaml
Observation:
  type: "object"
  required:
    - mouse_row
    - mouse_col
  properties:
    mouse_row:
      type: "number"
      format: "float"
      example: 1
      minimum: 0
      maximum: 5
      description: "Vertical mouse position ('row') between 0 and 5"
    mouse_col:
      type: "number"
      format: "float"
      example: 2
      minimum: 0
      maximum: 5
      description: "Horizontal mouse position ('col') between 0 and 5"
```

### output.yml
```yml
0: move up
1: move right
2: move down
3: move left
```
