### ISSUE TITLE
Generate `schema.yaml` file for python gym simulations

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#2880]
For the policy serving feature, #2847 we need a schema.yaml to set up the endpoint.

In this first version, the schema will be:
````yaml

parameters:
  discrete: True
  tuple: False
  api_key: "1234567asdfgh"

````

- the API key will be the users key from the webapp. This wiil be the only customized part of the file for now.
- This file will be saved in S3 for the policy server to be deployed when training is complete.

(Described here in the 'Raw predict endpoint' https://github.com/SkymindIO/policy-server#running-without-specifying-observations-in-schemayaml)
