### ISSUE TITLE
Add the runId to the schema.yaml

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#2988]
We use the `runId` to create the URL for policy serving. To be able to set the path for the docs, we will need the `runId` available in the schema.yaml

We'll add a param to the schema called:
`url_path` it's optional. If it doesn't exist then the policy server can assume it's at the root: `/`

Example:
```
parameters:
  discrete: True
  tuple: False
  api_key: "1234567asdfgh"
  url_path: 'policy/id1234`
```
