### ISSUE TITLE
Tweak Schema.yaml observations structure

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#3207]
Right now they look like this example:
```
observations:
  callCenters: List[float]
  hour: float
  currentCall: List[float]
  links: List[float]
  minute: float
```

We need to tweak it to include one more level of `type:` for each observation:
```
observations:
  callCenters: 
    type: List[float]
  hour: 
    type: float
  currentCall: 
    type: List[float]
  links: 
    type: List[float]
  minute: 
    type: float
```

This is set in `PolicyServerService.java` I think
