### ISSUE TITLE
Get the length of observation arrays

### ISSUE THREAD

**Issue by slinlee** [PathmindAI/pathmind-webapp#3258]
**Problem context:** When creating a policy server we use a schema.yaml to describe the observations that the user is meant to pass in. This is used by FastAPI to provide descriptive error messages and error checking. This works pretty well except for when the observation type is an array. (https://github.com/SkymindIO/policy-server/issues/67)

When it's an array, the expected length isn't defined, and if it's wrong, the server just replies with "Internal Server Error" to the user. The error logs are slightly more descriptive.

From the code below, it seems like we'll only know the expected length at the simulation runtime. 

- Definition of observation class
http://help.pathmind.com/en/articles/3631436-2-build-observation-space
  ````
  class Observations {
	double observation_0 = obs0;
	double observation_1 = obs1;
	double[] observation_2 = getObs_2()
  }
  ````

- Where observation classes are processed:
https://github.com/SkymindIO/nativerl/blob/6809ef392fe6cad5572a21aa70f6effd0bd7294c/nativerl-policy/src/main/java/ai/skymind/nativerl/ObservationProcessor.java

~~- [ ] **Can we have the model analyzer run a step to see what the shape/length the observations are and save that to the webapp DB** ?~~
~~- [ ] The length will be added to the schema.yaml as `minItems` and `maxItems` https://github.com/SkymindIO/policy-server/issues/67#issuecomment-868098151~~

Update from @kepricon - 
- This data is available in the database. So we just need to add it to the schema.yaml

The new schema.yaml change is this: For all 'List' type observations, we will include a `min_items` and `max_items` field that is set to the `max_items` column from this query below. min_items and max_items will be set to the same value.
![image](https://user-images.githubusercontent.com/1197406/123489174-469f0680-d5c6-11eb-938f-5cbc368a0b41.png)

So the new schema.yaml might look like:
```
parameters:
  discrete: true
  tuple: true
  api_key: 1234567asdfgh
  url_path: api/v1
observations:
  callCenters:
    type: List[float]
    min_items: 5
    max_items: 5
  hour:
    type: float
  currentCall:
    type: List[float]
    min_items: 29
    max_items: 29
  links:
    type: float

```
